name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        type: ["unes", "unesplus"]
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        runVcpkgInstall: false
        vcpkgGitCommitId: 739824a6d3179d85820eedc0637e81c0c68b874c
    - name: Get CMake
      uses: lukka/get-cmake@latest
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.type }}
        buildPreset: ${{ matrix.type }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: '${{ matrix.type }}-${{ matrix.name }}'
        path: build/unes/*UNES*
