name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job:
    name: ${{ matrix.os }}-${{ type }}-${{ github.workflow }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        type: ["unes", "unesplus"]
        config: ["Release", "Debug"]
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: Macos
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        runVcpkgInstall: false
        vcpkgGitCommitId: 739824a6d3179d85820eedc0637e81c0c68b874c
    - name: Get CMake
      uses: lukka/get-cmake@latest
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.type }}
        buildPreset: ${{ matrix.type }}
        buildPresetAdditionalArgs: ['--config ${{ matrix.config }}']
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: '${{ matrix.type }}-${{ matrix.name }}-${{ matrix.config }}'
        path: build/unes/*UNES*
  
  include:
    runs-on: ubuntu-latest
    steps:

